commit_message: 'translation: new %language% translations from Crowdin'
pull_request_title: 'translation: New Translations'
files:
  - source: /src/locales/en-US.json
    translation: /src/locales/%locale%.json
