name: Lint

on:
  push:
    branches:
      - production
      - preview
      - development
  pull_request:
    branches:
      - production
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Check for circular dependencies
        run: yarn run deps
